service: import-service

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::speedworks-products"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::speedworks-products/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events: 
      - http:
          path: /import
          method: GET
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: speedworks-products
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
